# Generated by Django 6.0 on 2025-12-27 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_recipient'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampaignDeliveryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], max_length=10)),
                ('failure_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_logs', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Campaign Delivery Log',
                'verbose_name_plural': 'Campaign Delivery Logs',
                'indexes': [models.Index(fields=['campaign', 'status'], name='campaigns_c_campaig_987ee4_idx')],
            },
        ),
    ]
